name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          base: header, activity, community              # Only display "header", "activity" and "community" sections
          repositories: 100                              # Query only last 100 repositories
          repositories_forks: no                         # Don't include forks
          repositories_affiliations: owner, collaborator # Display only repositories where user is owner or collaborator
          repositories_skipped: jullyanedemetrio/jullyanedemetrio    # Exclude automatically "lowlighter/lowlighter" repository from plugins allowing a skip list
          # Music Metrics
          plugin_music: yes
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_playlist: h                 # Use extracted playlist link
                                                  #   (plugin_music_provider and plugin_music_mode will be set automatically)
          #Most Used Languages
          plugin_languages: yes
          plugin_languages_skipped: jullyanedemetrio                   # List of repositories to skip
          
          #Coding Habits 
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          config_timezone: America/Sao_Paulo # Set timezone
          # Your GitHub token
          

